### ISSUE TITLE
Google Ad not showing between question and answer

### ISSUE THREAD

**Issue by gurjyot** [q2a-projects/CleanStrap#28]
I have added google adsense on my site in theme option > advertisement > advertisement in question page > after question content.

The ad shows when it is added "under question title" but it is not showing in "after question content".

**Comment by Towhidn** [comment]
right, I'll add another Adv locations when fixing this. thanks for reporting.

**Comment by gurjyot** [comment]
Hello @Towhidn, are you going to fix this issue and give some updates soon so that this theme can be used on Q2A 1.7. As the new google captcha is really what I need at the moment, but if I update Q2A then I lose this theme and I don't want that to happen. 
I am commenting for this because its almost 16 days since I raised this bug but there is no update for this theme.

**Comment by Towhidn** [comment]
CleanStrap is now compatible with Q2A 1.7
I'm planning to increase, re-arrange and improve widget positions in new version too.

**Comment by gurjyot** [comment]
Thanks for your reply... :)
