### ISSUE TITLE
Not compatible with open-login

### ISSUE THREAD

**Issue by fulldecent** [q2a-projects/CleanStrap#33]
It does not show up anywhere on the page

![screen shot 2015-03-11 at 3 13 41 pm](https://cloud.githubusercontent.com/assets/382183/6604785/5b08d0da-c801-11e4-9667-c7707571df56.png)

**Comment by Towhidn** [comment]
Right, popup login/register box doesn't show social login buttons. I'll add it to to-do list. for now social buttons are available on "site.com/login" URL.

**Comment by gautamshelley** [comment]
Still the open login isn't added to the modal, 

.... How to to add the open login to modal

**Comment by Dr-Hack** [comment]
Shouldnt this be closed and marked as fix ?

**Comment by Towhidn** [comment]
Yes it was resolved in one of previous updates. thanks for reminding me.

**Comment by Towhidn** [comment]
Yes it was resolved in one of previous updates. thanks for reminding me.
