### ISSUE TITLE
New Users Widget is showing only those who uploaded avatars

### ISSUE THREAD

**Issue by gurjyot** [q2a-projects/CleanStrap#37]
On your suggestion I tried the new feature of New Users widget, where only those users will be shown who have uploaded avatars. But now when I change that setting to "Show all users", then it is not showing all new users. Instead the widget is stuck to the first setting. How to go back??

**Comment by Towhidn** [comment]
I think this issue was previously solved. please confirm if this still exists.

**Comment by gurjyot** [comment]
I really don't know Towhid... Previously I was using this theme when you were updating this regularly... But when you stopped updating this then I had to change to SnowFlat as I cannot give incomplete user experience to my users. Sorry for this, and you can close this issue if you think the fix has been made.
